import assert from 'node:assert/strict';
import test from 'node:test';
import { createManualAiRequest, validateManualAiResponse } from '../lib/manual-ai';
import type { AnalysisFinding, Evaluation } from '../types/database';

const evaluation={id:'11111111-1111-4111-8111-111111111111',repo_name:'owner/repo',repo_url:'https://github.com/owner/repo',repo_stats:{commit_sha:'a'.repeat(40)},summary:'Deterministic summary',final_score:80,confidence_level:'90%',status:'completed'} as Evaluation;
const finding={id:'22222222-2222-4222-8222-222222222222',evaluation_id:evaluation.id,category:'architecture',severity:'medium',title:'Boundary issue',explanation:'A concrete boundary issue exists.',file_path:'src/app.ts',start_line:10,evidence:'evidence',recommendation:'Separate the boundary.',rule_id:'test.rule',confidence:90,created_at:new Date(0).toISOString()} as AnalysisFinding;
const valid={schema_version:'1.0',evaluation_id:evaluation.id,commit_sha:'a'.repeat(40),model_label:'ChatGPT',review_summary:'An evidence-grounded review summary for this repository.',confidence:84,architecture_observations:[{title:'Boundary',explanation:'The boundary combines unrelated application concerns.',impact:'medium',evidence_refs:[finding.id],confidence:82}],prioritized_risks:[{title:'Coupling risk',severity:'medium',explanation:'Tight coupling increases the cost of future changes.',evidence_refs:[finding.id],mitigation:'Separate transport and domain responsibilities.'}],recommendations:[{title:'Extract domain service',priority:1,rationale:'The cited boundary currently combines responsibilities.',evidence_refs:[finding.id],implementation_steps:['Create a focused service module.']}],rubric_advice:[{category:'architecture',suggested_delta:-1,rationale:'The deterministic evidence supports a small deduction.',evidence_refs:[finding.id]}]};

test('builds a bounded manual AI request with an explicit response schema',()=>{const request=createManualAiRequest(evaluation,[],[],[finding]);assert.equal(request.evaluation.id,evaluation.id);assert.equal(request.evidence_catalog[0].id,finding.id);assert.ok(request.required_response_schema.architecture_observations);});
test('accepts a structurally and semantically valid AI response',()=>{const result=validateManualAiResponse(valid,evaluation,[finding]);assert.equal(result.confidence,84);assert.equal(result.recommendations[0].priority,1);});
test('rejects unknown evidence references and mismatched commits',()=>{assert.throws(()=>validateManualAiResponse({...valid,commit_sha:'b'.repeat(40)},evaluation,[finding]),/commit_sha/);assert.throws(()=>validateManualAiResponse({...valid,architecture_observations:[{...valid.architecture_observations[0],evidence_refs:['33333333-3333-4333-8333-333333333333']}]},evaluation,[finding]),/Unknown evidence/);});
