'use client';
import { useCallback, useEffect, useState } from 'react';
import { Brain, Check, Clipboard, FileJson, Send, TriangleAlert } from 'lucide-react';
import type { ManualAiReview as Review } from '@/types/database';

export default function ManualAiReview({evaluationId}:{evaluationId:string}){
  const [request,setRequest]=useState<unknown>(null),[response,setResponse]=useState<Review|null>(null),[paste,setPaste]=useState(''),[error,setError]=useState(''),[copied,setCopied]=useState(false),[submitting,setSubmitting]=useState(false);
  const load=useCallback(async()=>{const result=await fetch(`/api/evaluations/${evaluationId}/ai-review`,{cache:'no-store'});if(result.ok){const data=await result.json();setRequest(data.request);setResponse(data.response);}else setError((await result.json()).error||'Unable to prepare AI request');},[evaluationId]);
  useEffect(()=>{load();},[load]);
  async function copy(){if(!request)return;await navigator.clipboard.writeText(JSON.stringify(request,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1500);}
  async function submit(){setError('');setSubmitting(true);try{let value:unknown;try{value=JSON.parse(paste);}catch{throw new Error('The pasted response is not valid JSON.');}const result=await fetch(`/api/evaluations/${evaluationId}/ai-review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await result.json();if(!result.ok)throw new Error(data.error||'Response validation failed');setResponse(data.response);setPaste('');}catch(value){setError(value instanceof Error?value.message:'Unable to import response');}finally{setSubmitting(false);}}
  return <div className="glass-card overflow-hidden">
    <div className="flex items-center justify-between gap-3 border-b border-border px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl border border-violet-500/20 bg-violet-500/10"><Brain size={17} className="text-violet-400" /></div><div><h3 className="text-sm font-semibold">Manual ChatGPT Review</h3><p className="text-xs text-muted-foreground">Evidence-grounded, human-in-the-loop AI analysis</p></div></div>{response&&<span className="flex items-center gap-1 rounded-full bg-emerald-500/10 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-400"><Check size={11}/> Validated</span>}</div>
    <div className="space-y-5 p-5">
      <div className="grid gap-3 sm:grid-cols-3">{[['1','Copy request JSON'],['2','Send it to ChatGPT'],['3','Paste JSON response']].map(([n,label])=><div key={n} className="flex items-center gap-2 rounded-lg border border-border bg-muted/30 p-3"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-violet-500/15 text-[10px] font-bold text-violet-400">{n}</span><span className="text-xs text-muted-foreground">{label}</span></div>)}</div>
      {!response&&<><div className="flex flex-wrap items-center gap-3"><button onClick={copy} disabled={!request} className="flex items-center gap-2 rounded-lg bg-violet-500 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-violet-400 disabled:opacity-50">{copied?<Check size={14}/>:<Clipboard size={14}/>} {copied?'Copied':'Copy ChatGPT Request JSON'}</button><span className="text-xs text-muted-foreground">Ask ChatGPT to return JSON only, without a markdown fence.</span></div>
        <div><label className="mb-2 flex items-center gap-2 text-xs font-semibold"><FileJson size={13} className="text-violet-400"/> ChatGPT response JSON</label><textarea value={paste} onChange={event=>setPaste(event.target.value)} rows={10} spellCheck={false} placeholder={'{"schema_version":"1.0", ...}'} className="w-full resize-y rounded-xl border border-border bg-slate-950 p-4 font-mono text-xs leading-relaxed text-slate-200 outline-none transition-colors placeholder:text-slate-600 focus:border-violet-500/50"/></div>
        <button onClick={submit} disabled={!paste.trim()||submitting} className="flex items-center gap-2 rounded-lg border border-violet-500/30 bg-violet-500/10 px-4 py-2 text-xs font-semibold text-violet-400 transition-colors hover:bg-violet-500/20 disabled:opacity-50"><Send size={13}/>{submitting?'Validating…':'Validate and Import Review'}</button></>}
      {error&&<div className="flex gap-2 rounded-lg border border-rose-500/20 bg-rose-500/10 p-3 text-xs text-rose-400"><TriangleAlert size={14} className="mt-0.5 shrink-0"/><span>{error}</span></div>}
      {response&&<div className="space-y-4"><div className="rounded-xl border border-violet-500/20 bg-violet-500/5 p-4"><div className="mb-2 flex items-center justify-between gap-3"><span className="text-xs font-semibold text-violet-400">{response.model_label}</span><span className="text-xs text-muted-foreground">AI confidence {response.confidence}%</span></div><p className="text-sm leading-relaxed text-muted-foreground">{response.review_summary}</p></div>
        {response.prioritized_risks.length>0&&<section><h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-rose-400">Prioritized risks</h4><div className="space-y-2">{response.prioritized_risks.map((risk,index)=><div key={index} className="rounded-lg border border-border p-3"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{risk.title}</p><span className="text-[10px] font-bold uppercase text-rose-400">{risk.severity}</span></div><p className="mt-1 text-xs text-muted-foreground">{risk.explanation}</p><p className="mt-2 text-xs text-emerald-400">Mitigation: {risk.mitigation}</p></div>)}</div></section>}
        {response.recommendations.length>0&&<section><h4 className="mb-2 text-xs font-semibold uppercase tracking-wider text-sky-400">AI recommendations</h4><div className="space-y-2">{response.recommendations.sort((a,b)=>a.priority-b.priority).map((item,index)=><div key={index} className="rounded-lg border border-border p-3"><p className="text-sm font-medium">P{item.priority} · {item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.rationale}</p><ol className="mt-2 list-inside list-decimal space-y-1 text-xs text-muted-foreground">{item.implementation_steps.map((step,i)=><li key={i}>{step}</li>)}</ol></div>)}</div></section>}
      </div>}
    </div>
  </div>;
}
