/** Mulya Astra — Google Sheets submission bridge.
 * Run setupMulyaAstra() once from Apps Script after setting Script Properties:
 * APP_BASE_URL, WEBHOOK_SECRET, DRIVE_FOLDER_ID and optionally ASSIGNMENT_SPEC_JSON.
 */
const HEADERS=['Student Name','Roll Number','Project Title','GitHub Repository','Evaluation ID','Status','Queue Position','Score','Grade','Report Link','Last Updated','Error'];

function setupMulyaAstra(){
  const sheet=SpreadsheetApp.getActiveSheet(),existing=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),1)).getDisplayValues()[0];if(existing.includes('Status')&&!existing.includes('Queue Position'))sheet.insertColumnAfter(existing.indexOf('Status')+1);sheet.getRange(1,1,1,HEADERS.length).setValues([HEADERS]).setFontWeight('bold');sheet.setFrozenRows(1);
  ScriptApp.getProjectTriggers().filter(t=>['submitEditedRow','processPendingReports'].includes(t.getHandlerFunction())).forEach(t=>ScriptApp.deleteTrigger(t));
  ScriptApp.newTrigger('submitEditedRow').forSpreadsheet(SpreadsheetApp.getActive()).onEdit().create();
  ScriptApp.newTrigger('processPendingReports').timeBased().everyMinutes(5).create();
}

function config_(){const p=PropertiesService.getScriptProperties(),base=(p.getProperty('APP_BASE_URL')||'').replace(/\/$/,'');const secret=p.getProperty('WEBHOOK_SECRET'),folder=p.getProperty('DRIVE_FOLDER_ID');if(!base||!secret||!folder)throw new Error('Set APP_BASE_URL, WEBHOOK_SECRET, and DRIVE_FOLDER_ID in Script Properties.');return {base,secret,folder,spec:p.getProperty('ASSIGNMENT_SPEC_JSON'),share:p.getProperty('SHARE_REPORTS_WITH_LINK')==='true'};}
function columns_(sheet){const values=sheet.getRange(1,1,1,sheet.getLastColumn()).getDisplayValues()[0],map={};values.forEach((v,i)=>map[v]=i+1);HEADERS.forEach(h=>{if(!map[h])throw new Error('Missing column: '+h);});return map;}
function request_(url,method,payload){const c=config_(),response=UrlFetchApp.fetch(url,{method:method||'get',contentType:'application/json',headers:{Authorization:'Bearer '+c.secret},payload:payload?JSON.stringify(payload):undefined,muteHttpExceptions:true});const text=response.getContentText();if(response.getResponseCode()<200||response.getResponseCode()>=300)throw new Error('Application returned '+response.getResponseCode()+': '+text.slice(0,300));return JSON.parse(text);}

function submitEditedRow(e){const sheet=e.range.getSheet(),col=columns_(sheet);if(e.range.getRow()===1||e.range.getColumn()!==col['GitHub Repository']||!String(e.value||'').trim())return;submitRow_(sheet,e.range.getRow(),col);}
function submitRow_(sheet,row,col){const lock=LockService.getDocumentLock();lock.waitLock(10000);try{if(sheet.getRange(row,col['Evaluation ID']).getValue())return;const c=config_(),body={studentName:sheet.getRange(row,col['Student Name']).getDisplayValue(),rollNumber:sheet.getRange(row,col['Roll Number']).getDisplayValue(),projectTitle:sheet.getRange(row,col['Project Title']).getDisplayValue(),repoUrl:sheet.getRange(row,col['GitHub Repository']).getDisplayValue(),assignmentSpec:c.spec?JSON.parse(c.spec):null};sheet.getRange(row,col.Status).setValue('Queued');const result=request_(c.base+'/api/integrations/google-sheets','post',body);sheet.getRange(row,col['Evaluation ID']).setValue(result.evaluationId);sheet.getRange(row,col.Status).setValue('Queued');sheet.getRange(row,col['Queue Position']).setValue(result.queuePosition||1);sheet.getRange(row,col['Last Updated']).setValue(new Date());sheet.getRange(row,col.Error).clearContent();}catch(error){sheet.getRange(row,col.Status).setValue('Error');sheet.getRange(row,col.Error).setValue(String(error).slice(0,500));}finally{lock.releaseLock();}}

function processPendingReports(){const sheet=SpreadsheetApp.getActiveSheet(),col=columns_(sheet),last=sheet.getLastRow();if(last<2)return;for(let row=2;row<=last;row++){const status=sheet.getRange(row,col.Status).getDisplayValue(),id=sheet.getRange(row,col['Evaluation ID']).getDisplayValue();if(!id||!['Queued','In Progress'].includes(status))continue;try{const c=config_(),data=request_(c.base+'/api/integrations/google-sheets?evaluationId='+encodeURIComponent(id),'get');sheet.getRange(row,col.Status).setValue(data.evaluation.pipelineStatus);if(data.evaluation.pipelineStatus==='Queued')sheet.getRange(row,col['Queue Position']).setValue(data.evaluation.queuePosition||1);else sheet.getRange(row,col['Queue Position']).clearContent();sheet.getRange(row,col['Last Updated']).setValue(new Date());if(data.evaluation.pipelineStatus==='Completed'){sheet.getRange(row,col.Status).setValue('In Progress');const url=createReport_(data,c);sheet.getRange(row,col.Score).setValue(data.evaluation.score);sheet.getRange(row,col.Grade).setValue(data.evaluation.grade);sheet.getRange(row,col['Report Link']).setFormula('=HYPERLINK("'+url+'","View / download report")');sheet.getRange(row,col.Status).setValue('Completed');}else if(data.evaluation.pipelineStatus==='Failed')throw new Error('Evaluation failed');}catch(error){sheet.getRange(row,col.Status).setValue('Error');sheet.getRange(row,col.Error).setValue(String(error).slice(0,500));}}}

function createReport_(data,c){const e=data.evaluation,doc=DocumentApp.create(e.projectTitle+' — '+e.studentName+' — Evaluation'),body=doc.getBody();body.appendParagraph('Repository Evaluation Report').setHeading(DocumentApp.ParagraphHeading.TITLE);body.appendParagraph(e.studentName+' ('+e.rollNumber+')');body.appendParagraph(e.projectTitle).setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph('Repository: '+e.repository);body.appendParagraph('Score: '+e.score+'/100  •  Grade: '+e.grade+'  •  Confidence: '+e.confidence);body.appendParagraph('Summary').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph(e.summary||'');body.appendParagraph('Score Breakdown').setHeading(DocumentApp.ParagraphHeading.HEADING1);data.categoryScores.forEach(s=>body.appendListItem(s.category+': '+s.score+'/'+s.max_score+' — '+s.rationale));if(e.assignment){body.appendParagraph('Assignment Compliance').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph(e.assignment.summary);e.assignment.checks.forEach(x=>body.appendListItem(x.status.toUpperCase()+': '+x.requirement));}body.appendParagraph('Priority Findings').setHeading(DocumentApp.ParagraphHeading.HEADING1);data.findings.forEach(f=>body.appendListItem('['+f.severity.toUpperCase()+'] '+f.title+' — '+f.explanation+(f.file_path?' ('+f.file_path+(f.start_line?':'+f.start_line:'')+')':'')));body.appendParagraph('Improvement Roadmap').setHeading(DocumentApp.ParagraphHeading.HEADING1);body.appendParagraph(e.roadmap||'');doc.saveAndClose();const folder=DriveApp.getFolderById(c.folder),docFile=DriveApp.getFileById(doc.getId());docFile.moveTo(folder);const pdf=folder.createFile(docFile.getBlob().getAs(MimeType.PDF)).setName(doc.getName()+'.pdf');if(c.share)pdf.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return pdf.getUrl();}

function retrySelectedRow(){const sheet=SpreadsheetApp.getActiveSheet(),row=sheet.getActiveRange().getRow(),col=columns_(sheet);sheet.getRange(row,col['Evaluation ID']).clearContent();sheet.getRange(row,col.Status).clearContent();sheet.getRange(row,col['Queue Position']).clearContent();sheet.getRange(row,col.Error).clearContent();submitRow_(sheet,row,col);}
