import type { AssignmentCheck, AssignmentEvaluation, AssignmentSpec } from '@/types/database';
import type { RepositorySnapshot, SourceFile } from './github-analysis';

const norm=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,'');
const codeFile=(file:SourceFile)=>/\.(?:[cm]?[jt]sx?|py|html?|css|scss)$/.test(file.path);
const evidence=(file:SourceFile,needle:string)=>`${file.path}: ${needle.slice(0,140)}`;

export function evaluateAssignment(snapshot:RepositorySnapshot,spec:AssignmentSpec,engineeringScore:number):AssignmentEvaluation{
  const checks:AssignmentCheck[]=[];const files=snapshot.files;let index=0;
  const add=(category:AssignmentCheck['category'],requirement:string,passed:boolean,found:string[]=[],needsAi=false)=>checks.push({id:`${category}-${++index}`,category,requirement,status:needsAi?'needs_ai':passed?'passed':'failed',points:passed?1:0,max_points:needsAi?0:1,evidence:found.slice(0,5),explanation:needsAi?'Requires visual or semantic judgment in the manual AI review.':passed?'Requirement was found in the pinned repository snapshot.':'No matching evidence was found in the pinned repository snapshot.'});

  for(const required of spec.required_paths){const clean=required.replace(/^\.\//,'').replace(/\*+/g,'');const matches=files.filter(f=>f.path===clean||f.path.startsWith(clean.replace(/\/$/,'')+'/')||f.path.includes(clean));add('architecture',required,matches.length>0,matches.map(f=>f.path));}
  for(const name of spec.required_functions){const token=name.replace(/[^A-Za-z0-9_$]/g,'');const pattern=new RegExp(`(?:function\\s+${token}\\b|(?:const|let|var)\\s+${token}\\s*=|def\\s+${token}\\s*\\(|(?:async\\s+)?${token}\\s*\\([^)]*\\)\\s*\\{)`);const matches=files.filter(f=>codeFile(f)&&pattern.test(f.content));add('functions',name,matches.length>0,matches.map(f=>evidence(f,name)));}
  for(const requirement of spec.ui_requirements){const tokens=requirement.toLowerCase().match(/[a-z0-9]{3,}/g)?.filter(t=>!['with','that','this','should','must','have','using'].includes(t))||[];const ui=files.filter(f=>/\.(?:tsx?|jsx?|html?|css|scss)$/.test(f.path));const matches=ui.filter(f=>tokens.some(t=>f.content.toLowerCase().includes(t)));add('ui',requirement,matches.length>0,matches.map(f=>evidence(f,requirement)),tokens.length===0);}
  for(const requirement of spec.model_requirements){const target=norm(requirement);const aliases=[target,target.replace('regression','regressor'),target.replace('classifier','classification')];const matches=files.filter(f=>/\.(?:py|[cm]?[jt]s|json|txt)$/.test(f.path)&&aliases.some(alias=>norm(f.content).includes(alias)));add('model',requirement,matches.length>0,matches.map(f=>evidence(f,requirement)));}
  for(const endpoint of spec.endpoints){const method=endpoint.method.toLowerCase(),path=endpoint.path.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const patterns=[new RegExp(`\\.(?:${method})\\s*\\(\\s*['\"]${path}['\"]`,'i'),new RegExp(`@(?:app|router)\\.${method}\\s*\\(\\s*['\"]${path}['\"]`,'i')];const routePath=endpoint.path.replace(/^\//,'');const matches=files.filter(f=>patterns.some(p=>p.test(f.content))||new RegExp(`(?:app|pages)/api/${routePath.replace(/:[^/]+/g,'[^/]+')}/route\\.[jt]s$`,'i').test(f.path)&&new RegExp(`export\\s+(?:async\\s+)?function\\s+${method}`,'i').test(f.content));add('endpoints',`${endpoint.method.toUpperCase()} ${endpoint.path}${endpoint.description?` — ${endpoint.description}`:''}`,matches.length>0,matches.map(f=>f.path));}
  for(const forbidden of spec.forbidden_patterns){const matches=files.filter(f=>codeFile(f)&&f.content.toLowerCase().includes(forbidden.toLowerCase()));add('constraints',`Must not use: ${forbidden}`,matches.length===0,matches.map(f=>evidence(f,forbidden)));}
  if(spec.brief.trim())add('constraints','Instructor brief requires semantic review',false,[],true);

  const scored=checks.filter(c=>c.max_points>0),passed=scored.filter(c=>c.status==='passed').length;const compliance=scored.length?Math.round(passed/scored.length*100):0;const weight=scored.length?Math.min(100,Math.max(0,spec.assignment_weight||70)):0;const final=Math.round((compliance*weight+engineeringScore*(100-weight))/100);
  return {compliance_score:compliance,engineering_score:engineeringScore,final_weighted_score:final,assignment_weight:weight,checks,summary:scored.length?`${passed} of ${scored.length} explicit instructor requirements passed deterministic verification. ${checks.some(c=>c.status==='needs_ai')?'The brief still requires manual AI review.':''}`:'No explicit machine-verifiable rules were supplied; the instructor brief requires manual AI review.'};
}
