import ts from 'typescript';
import type { AnalysisFinding, CategoryScore } from '@/types/database';

export interface RepoMetadata { name:string; description:string|null; stargazers_count:number; forks_count:number; language:string|null; default_branch:string; topics:string[] }
interface TreeItem { path:string; type:'blob'|'tree'; sha:string; size?:number; url:string }
export interface SourceFile { path:string; content:string; size:number; language:string; lines:number }
export interface RepositorySnapshot { metadata:RepoMetadata; commitSha:string; files:SourceFile[]; treeCount:number; truncated:boolean }
const MAX_FILES=500, MAX_FILE_BYTES=300_000, MAX_TOTAL_BYTES=15_000_000;
const SOURCE_EXTENSIONS=new Set(['.ts','.tsx','.js','.jsx','.mjs','.cjs','.py','.html','.htm','.json','.md','.yml','.yaml','.css','.scss','.txt']);
const ignored=/(^|\/)(node_modules|vendor|dist|build|\.next|coverage|generated|fixtures?\/large)(\/|$)|\.min\.(js|css)$|(^|\/)(package-lock|yarn\.lock|pnpm-lock\.yaml)$/i;

function headers(){const h:Record<string,string>={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Mulya-Astra/1.0'};if(process.env.GITHUB_TOKEN)h.Authorization=`Bearer ${process.env.GITHUB_TOKEN}`;return h;}
async function github<T>(path:string):Promise<T>{const response=await fetch(`https://api.github.com${path}`,{headers:headers(),cache:'no-store'});if(!response.ok)throw new Error(`GitHub API ${response.status}: ${await response.text().then(t=>t.slice(0,200))}`);return response.json();}
function extension(path:string){const index=path.lastIndexOf('.');return index<0?'':path.slice(index).toLowerCase();}
function language(path:string){return ({'.ts':'TypeScript','.tsx':'TypeScript React','.js':'JavaScript','.jsx':'JavaScript React','.mjs':'JavaScript','.cjs':'JavaScript','.py':'Python','.html':'HTML','.htm':'HTML','.json':'JSON','.md':'Markdown','.yml':'YAML','.yaml':'YAML','.css':'CSS','.scss':'SCSS'} as Record<string,string>)[extension(path)]||'Text';}
function candidate(item:TreeItem){return item.type==='blob'&&!ignored.test(item.path)&&SOURCE_EXTENSIONS.has(extension(item.path))&&(extension(item.path)!=='.txt'||/(^|\/)requirements(?:-[^/]+)?\.txt$/i.test(item.path))&&(item.size||0)<=MAX_FILE_BYTES;}

export async function fetchSnapshot(owner:string,repo:string):Promise<RepositorySnapshot>{
  const metadata=await github<RepoMetadata>(`/repos/${owner}/${repo}`);
  const branch=await github<{commit:{sha:string}}>(`/repos/${owner}/${repo}/branches/${encodeURIComponent(metadata.default_branch)}`);
  const tree=await github<{tree:TreeItem[];truncated:boolean}>(`/repos/${owner}/${repo}/git/trees/${branch.commit.sha}?recursive=1`);
  const selected:TreeItem[]=[];let bytes=0;
  for(const item of tree.tree){if(!candidate(item))continue;const size=item.size||0;if(selected.length>=MAX_FILES||bytes+size>MAX_TOTAL_BYTES)break;selected.push(item);bytes+=size;}
  const files:SourceFile[]=[];
  for(let i=0;i<selected.length;i+=10){const batch=selected.slice(i,i+10);const values=await Promise.all(batch.map(async item=>{const blob=await github<{content:string;encoding:string}>(`/repos/${owner}/${repo}/git/blobs/${item.sha}`);const content=blob.encoding==='base64'?Buffer.from(blob.content.replace(/\n/g,''),'base64').toString('utf8'):blob.content;return {path:item.path,content,size:Buffer.byteLength(content),language:language(item.path),lines:content.split(/\r?\n/).length};}));files.push(...values);}
  return {metadata,commitSha:branch.commit.sha,files,treeCount:tree.tree.filter(i=>i.type==='blob').length,truncated:tree.truncated||selected.length>=MAX_FILES||files.reduce((n,f)=>n+f.size,0)>=MAX_TOTAL_BYTES};
}

type FindingInput=Omit<AnalysisFinding,'id'|'evaluation_id'|'created_at'>;
const finding=(value:FindingInput)=>value;
export interface FrontendAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{componentFiles:number;components:number;typescriptCoverage:number;hooks:number;accessibilityIssues:number;frontendTests:number} }
export interface BackendAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{backendFiles:number;endpointFiles:number;databaseFiles:number;validatedEndpoints:number;backendTests:number;reliabilityIssues:number} }
export interface UiUxAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{uiFiles:number;semanticLandmarks:number;accessibilityIssues:number;responsiveSignals:number;feedbackSignals:number;designSystemSignals:number;uiTests:number} }
export interface AiMlAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{aiFiles:number;providers:number;modelCalls:number;validatedOutputs:number;reliabilityControls:number;safetyIssues:number;aiTests:number} }
export interface SecurityAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{codeFiles:number;endpointFiles:number;protectedEndpoints:number;criticalIssues:number;highIssues:number;securityTests:number} }
export interface ProductAssessment { applicable:boolean; score:number|null; grade:string; confidence:number; summary:string; strengths:string[]; weaknesses:string[]; suggestions:string[]; metrics:{applicationFiles:number;documentedCapabilities:number;feedbackStates:number;operabilitySignals:number;deliverySignals:number;productTests:number} }
function frontendGrade(score:number){return score>=90?'Exceptional':score>=80?'Excellent':score>=70?'Good':score>=60?'Developing':'Needs Improvement';}
function jsxName(node:ts.JsxOpeningLikeElement){return node.tagName.getText();}
function hasJsxAttribute(node:ts.JsxOpeningLikeElement,name:string){return node.attributes.properties.some(p=>ts.isJsxAttribute(p)&&p.name.getText()===name);}

function analyzeFrontend(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):FrontendAssessment{
  const componentFiles=files.filter(f=>/\.[jt]sx$/.test(f.path));const htmlFiles=files.filter(f=>/\.html?$/.test(f.path));const staticJs=files.filter(f=>/\.(js|mjs)$/.test(f.path)&&/(^|\/)(static|public|assets)(\/|$)/i.test(f.path));const frontendFiles=[...componentFiles,...htmlFiles,...staticJs];
  if(!frontendFiles.length)return {applicable:false,score:null,grade:'Not Applicable',confidence:95,summary:'No JSX/TSX or static HTML frontend surface was detected, so no frontend grade was assigned.',strengths:[],weaknesses:[],suggestions:[],metrics:{componentFiles:0,components:0,typescriptCoverage:0,hooks:0,accessibilityIssues:0,frontendTests:0}};
  let components=0,hooks=0,accessibilityIssues=0,indexKeys=0,rawImages=0,largeComponents=0,effectsWithoutDeps=0;const issueLimit=20;
  const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('frontend.')).length<issueLimit)findings.push(finding(value));};
  for(const file of componentFiles){const source=ts.createSourceFile(file.path,file.content,ts.ScriptTarget.Latest,true,file.path.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.JSX);
    const visit=(node:ts.Node)=>{
      let componentName:string|null=null,body:ts.Node|undefined;
      if(ts.isFunctionDeclaration(node)&&node.name&&/^[A-Z]/.test(node.name.text)){componentName=node.name.text;body=node.body;}
      if(ts.isVariableDeclaration(node)&&ts.isIdentifier(node.name)&&/^[A-Z]/.test(node.name.text)&&node.initializer&&(ts.isArrowFunction(node.initializer)||ts.isFunctionExpression(node.initializer))){componentName=node.name.text;body=node.initializer.body;}
      if(componentName&&body){components++;const start=source.getLineAndCharacterOfPosition(node.getStart()).line+1,end=source.getLineAndCharacterOfPosition(node.getEnd()).line+1;if(end-start+1>180){largeComponents++;add({category:'architecture',severity:'medium',title:`Large frontend component: ${componentName}`,explanation:`The component spans ${end-start+1} lines, which makes rendering, state, and interaction concerns harder to isolate.`,file_path:file.path,start_line:start,evidence:`${componentName}: ${end-start+1} lines`,recommendation:'Extract focused view components and move reusable state or data logic into hooks.',rule_id:'frontend.large-component',confidence:95});}}
      if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression)&&/^use[A-Z]/.test(node.expression.text)){hooks++;if(node.expression.text==='useEffect'&&node.arguments.length<2){effectsWithoutDeps++;const line=source.getLineAndCharacterOfPosition(node.getStart()).line+1;add({category:'quality',severity:'medium',title:'Effect has no dependency array',explanation:'This effect runs after every render and can cause repeated work or update loops.',file_path:file.path,start_line:line,evidence:node.getText(source).slice(0,140),recommendation:'Declare intentional dependencies or restructure the effect so its lifecycle is explicit.',rule_id:'frontend.effect-dependencies',confidence:90});}}
      if(ts.isJsxOpeningElement(node)||ts.isJsxSelfClosingElement(node)){const tag=jsxName(node).toLowerCase(),line=source.getLineAndCharacterOfPosition(node.getStart()).line+1;
        if(tag==='img'&&!hasJsxAttribute(node,'alt')){accessibilityIssues++;add({category:'quality',severity:'high',title:'Image is missing alternative text',explanation:'Images without alt text are not meaningfully exposed to screen readers.',file_path:file.path,start_line:line,evidence:node.getText(source).slice(0,160),recommendation:'Add an accurate alt value, or alt="" for a decorative image.',rule_id:'frontend.image-alt',confidence:98});}
        if(tag==='img'){rawImages++;}
        if(['div','span'].includes(tag)&&hasJsxAttribute(node,'onClick')&&!hasJsxAttribute(node,'role')&&!hasJsxAttribute(node,'tabIndex')){accessibilityIssues++;add({category:'quality',severity:'high',title:'Non-interactive element used as a control',explanation:`A clickable <${tag}> is not keyboard-accessible by default.`,file_path:file.path,start_line:line,evidence:node.getText(source).slice(0,160),recommendation:'Use a semantic button/link, or provide complete keyboard and ARIA behavior.',rule_id:'frontend.nonsemantic-control',confidence:92});}
        const key=node.attributes.properties.find(p=>ts.isJsxAttribute(p)&&p.name.getText()==='key');if(key&&/\b(index|i)\b/.test(key.getText(source))){indexKeys++;add({category:'performance',severity:'medium',title:'Array index used as React key',explanation:'Index keys can associate component state with the wrong item after insertion or reordering.',file_path:file.path,start_line:line,evidence:key.getText(source),recommendation:'Use a stable identifier derived from the item.',rule_id:'frontend.index-key',confidence:85});}
      }
      ts.forEachChild(node,visit);};visit(source);
  }
  for(const file of staticJs){const source=ts.createSourceFile(file.path,file.content,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);source.forEachChild(node=>{if(ts.isFunctionDeclaration(node)||(ts.isVariableStatement(node)&&node.declarationList.declarations.some(d=>Boolean(d.initializer&&(ts.isArrowFunction(d.initializer)||ts.isFunctionExpression(d.initializer))))))components++;});if(file.lines>400){largeComponents++;add({category:'architecture',severity:'medium',title:'Oversized static frontend script',explanation:`The browser script contains ${file.lines} lines, increasing coupling between DOM, state, and network behavior.`,file_path:file.path,start_line:1,evidence:`${file.lines} lines`,recommendation:'Split DOM rendering, API access, state, and event handling into focused ES modules.',rule_id:'frontend.large-static-script',confidence:92});}}
  const tsFiles=componentFiles.filter(f=>f.path.endsWith('.tsx')).length,typescriptCoverage=componentFiles.length?Math.round(tsFiles/componentFiles.length*100):0,frontendTests=allTests.filter(f=>/\.[jt]sx?$/.test(f.path)&&/(ui|frontend|dom|browser|static|component)/i.test(f.path+' '+f.content.slice(0,800))).length;
  const architecture=Math.max(10,25-largeComponents*5),typing=componentFiles.length?Math.round(20*typescriptCoverage/100):8,accessibility=Math.max(5,20-accessibilityIssues*4),state=Math.max(7,15-effectsWithoutDeps*3),performance=Math.max(4,10-indexKeys*2-Math.min(rawImages,2)),testing=frontendTests===0?2:frontendTests/frontendFiles.length>=.2?10:6;const score=architecture+typing+accessibility+state+performance+testing;
  const strengths:string[]=[];if(typescriptCoverage>=80)strengths.push(`${typescriptCoverage}% of component files use TypeScript`);if(accessibilityIssues===0)strengths.push('No high-confidence static accessibility violations detected');if(largeComponents===0)strengths.push('Components stay below the oversized-component threshold');if(frontendTests>0)strengths.push(`${frontendTests} frontend test file${frontendTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(accessibilityIssues)weaknesses.push(`${accessibilityIssues} accessibility issue${accessibilityIssues===1?'':'s'} detected`);if(largeComponents)weaknesses.push(`${largeComponents} oversized component${largeComponents===1?'':'s'} detected`);if(typescriptCoverage<80)weaknesses.push(`TypeScript component coverage is ${typescriptCoverage}%`);if(!frontendTests)weaknesses.push('No frontend tests detected');if(effectsWithoutDeps)weaknesses.push(`${effectsWithoutDeps} effect${effectsWithoutDeps===1?'':'s'} run after every render`);
  const suggestions=Array.from(new Set(findings.filter(f=>f.rule_id.startsWith('frontend.')).map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?70:90,summary:`Frontend grade: ${frontendGrade(score)} (${score}/100). Reviewed ${components} components/modules across ${frontendFiles.length} frontend files (${htmlFiles.length} static HTML, ${staticJs.length} static JavaScript, ${componentFiles.length} JSX/TSX) for structure, typing, accessibility, state, rendering stability, and tests.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{componentFiles:frontendFiles.length,components,typescriptCoverage,hooks,accessibilityIssues,frontendTests}};
}

function analyzeBackend(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):BackendAssessment{
  const packageFiles=files.filter(f=>f.path.endsWith('package.json'));let dependencies:Record<string,string>={};for(const file of packageFiles){try{const value=JSON.parse(file.content);dependencies={...dependencies,...value.dependencies,...value.devDependencies};}catch{/* malformed manifests are handled by other checks */}}
  const serverDependency=/^(express|fastify|koa|hapi|nestjs|@nestjs\/core|prisma|@prisma\/client|mongoose|sequelize|typeorm|drizzle-orm|better-sqlite3|pg|mysql2|firebase-admin)$/;
  const requirements=files.filter(f=>/(^|\/)requirements(?:-[^/]+)?\.txt$/i.test(f.path)).map(f=>f.content).join('\n');
  const backendFiles=files.filter(f=>/\.(ts|js|mjs|cjs|py)$/.test(f.path)&&(/(^|\/)(api|server|backend|controllers?|services?|repositories|database|db)(\/|$)/i.test(f.path)||/(^|\/)(route|db|database)\.[jt]s$/.test(f.path)||/@(?:app|router)\.(?:get|post|put|patch|delete)\s*\(/.test(f.content)));
  const applicable=backendFiles.length>0||Object.keys(dependencies).some(d=>serverDependency.test(d))||/\b(fastapi|flask|django|sqlalchemy|uvicorn|pydantic)\b/i.test(requirements);
  if(!applicable)return {applicable:false,score:null,grade:'Not Applicable',confidence:90,summary:'No server routes, backend modules, or server-side dependencies were detected.',strengths:[],weaknesses:[],suggestions:[],metrics:{backendFiles:0,endpointFiles:0,databaseFiles:0,validatedEndpoints:0,backendTests:0,reliabilityIssues:0}};
  const endpointFiles=backendFiles.filter(f=>/(^|\/)(api|routes?|controllers?)(\/|$)|(^|\/)route\.[jt]s$/i.test(f.path)||/@(?:app|router)\.(?:get|post|put|patch|delete)\s*\(/.test(f.content));const databaseFiles=backendFiles.filter(f=>/(^|\/)(database|db|repositories|migrations?)(\/|$)|prisma|drizzle|mongoose|sequelize|typeorm|sqlalchemy/i.test(f.path+' '+f.content.slice(0,500)));const backendTests=allTests.filter(f=>backendFiles.some(b=>f.path.includes(b.path.split('/').slice(0,-1).join('/')))).length;
  let validatedEndpoints=0,reliabilityIssues=0,unvalidated=0,unsafeQueries=0,envAssertions=0,oversized=0;const issueLimit=24;
  const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('backend.')).length<issueLimit)findings.push(finding(value));};
  const lineOf=(content:string,index:number)=>content.slice(0,index).split(/\r?\n/).length;
  for(const file of backendFiles){
    const bodyRead=/(?:req|request)\.json\s*\(|(?:req|request)\.body\b/.exec(file.content);const validation=/\b(z\.|zod|safeParse|\.parse\s*\(|joi\.|yup\.|valibot|class-validator)\b/i.test(file.content);if(endpointFiles.includes(file)&&validation)validatedEndpoints++;
    if(endpointFiles.includes(file)&&bodyRead&&!validation){unvalidated++;add({category:'security',severity:'high',title:'Request body is used without schema validation',explanation:'The endpoint reads caller-controlled data without a detected runtime schema boundary.',file_path:file.path,start_line:lineOf(file.content,bodyRead.index),evidence:bodyRead[0],recommendation:'Validate and normalize request data with a schema before business logic or persistence.',rule_id:'backend.input-validation',confidence:88});}
    const fetchCalls=Array.from(file.content.matchAll(/await\s+fetch\s*\([^;]+/g));for(const match of fetchCalls){const nearby=file.content.slice(match.index||0,(match.index||0)+500);if(!/\.ok\b|status\b/.test(nearby)){reliabilityIssues++;add({category:'quality',severity:'medium',title:'External response status is not checked',explanation:'A network call appears to consume or return a response without validating failure status.',file_path:file.path,start_line:lineOf(file.content,match.index||0),evidence:match[0].slice(0,150),recommendation:'Check response.ok/status and map upstream failures into explicit application errors.',rule_id:'backend.fetch-status',confidence:78});}}
    const env=Array.from(file.content.matchAll(/process\.env\.[A-Z0-9_]+!/g));if(env.length){envAssertions+=env.length;add({category:'architecture',severity:'medium',title:'Environment configuration is asserted, not validated',explanation:'Non-null assertions defer missing configuration failures until the affected code path runs.',file_path:file.path,start_line:lineOf(file.content,env[0].index||0),evidence:env.slice(0,3).map(v=>v[0]).join(', '),recommendation:'Validate required environment variables once at process startup using a typed schema.',rule_id:'backend.env-validation',confidence:92});}
    const sql=/\b(?:exec|query|prepare)\s*\([^;]{0,500}\$\{/m.exec(file.content);if(sql){unsafeQueries++;add({category:'security',severity:'critical',title:'Dynamic value interpolated into SQL',explanation:'Template interpolation in a SQL statement can create an injection boundary.',file_path:file.path,start_line:lineOf(file.content,sql.index),evidence:sql[0].slice(0,160),recommendation:'Use bound parameters for every dynamic value and allow-list identifiers.',rule_id:'backend.sql-interpolation',confidence:84});}
    if(file.lines>500){oversized++;add({category:'architecture',severity:'medium',title:'Oversized backend module',explanation:`The backend module contains ${file.lines} lines and likely combines transport, domain, and persistence concerns.`,file_path:file.path,start_line:1,evidence:`${file.lines} lines`,recommendation:'Separate route adapters, domain services, repositories, and external integrations.',rule_id:'backend.large-module',confidence:90});}
  }
  const api=Math.max(7,20-unvalidated*4),architecture=Math.max(8,20-oversized*4-envAssertions*2),persistence=databaseFiles.length?Math.max(10,20-unsafeQueries*8):12,security=Math.max(4,15-unvalidated*4-unsafeQueries*7),reliability=Math.max(6,15-reliabilityIssues*3),testing=backendTests===0?2:backendTests/backendFiles.length>=.15?10:6;const score=api+architecture+persistence+security+reliability+testing;
  const strengths:string[]=[];if(validatedEndpoints)strengths.push(`${validatedEndpoints} endpoint file${validatedEndpoints===1?' uses':'s use'} runtime schema validation`);if(databaseFiles.length)strengths.push(`${databaseFiles.length} persistence or migration module${databaseFiles.length===1?'':'s'} detected`);if(!unsafeQueries)strengths.push('No high-confidence interpolated SQL was detected');if(!reliabilityIssues)strengths.push('Detected external requests include explicit failure handling');if(backendTests)strengths.push(`${backendTests} backend test file${backendTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(unvalidated)weaknesses.push(`${unvalidated} endpoint file${unvalidated===1?' reads':'s read'} input without detected schema validation`);if(reliabilityIssues)weaknesses.push(`${reliabilityIssues} external request${reliabilityIssues===1?' lacks':'s lack'} explicit status handling`);if(envAssertions)weaknesses.push(`${envAssertions} environment value${envAssertions===1?' is':'s are'} asserted without startup validation`);if(oversized)weaknesses.push(`${oversized} oversized backend module${oversized===1?'':'s'}`);if(!backendTests)weaknesses.push('No backend tests were associated with detected backend modules');
  const suggestions=Array.from(new Set(findings.filter(f=>f.rule_id.startsWith('backend.')).map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?68:88,summary:`Backend grade: ${frontendGrade(score)} (${score}/100). Reviewed ${backendFiles.length} backend modules, ${endpointFiles.length} endpoint files, and ${databaseFiles.length} persistence modules for contracts, boundaries, data access, validation, reliability, and tests.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{backendFiles:backendFiles.length,endpointFiles:endpointFiles.length,databaseFiles:databaseFiles.length,validatedEndpoints,backendTests,reliabilityIssues}};
}

function analyzeUiUx(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):UiUxAssessment{
  const uiFiles=files.filter(f=>/\.[jt]sx$|\.html?$/i.test(f.path));if(!uiFiles.length)return {applicable:false,score:null,grade:'Not Applicable',confidence:95,summary:'No JSX/TSX or static HTML interface surface was detected, so no UI/UX grade was assigned.',strengths:[],weaknesses:[],suggestions:[],metrics:{uiFiles:0,semanticLandmarks:0,accessibilityIssues:0,responsiveSignals:0,feedbackSignals:0,designSystemSignals:0,uiTests:0}};
  let landmarks=0,a11y=0,responsive=0,feedback=0,design=0,iconButtons=0,formLabels=0,inputs=0;const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('uiux.')).length<24)findings.push(finding(value));};
  for(const file of uiFiles){responsive+=(file.content.match(/\b(?:sm|md|lg|xl|2xl):|@media|name=['"]viewport['"]/gi)||[]).length;feedback+=(file.content.match(/\b(?:loading|isLoading|pending|error|toast|skeleton|spinner|disabled)\b/gi)||[]).length;design+=(file.content.match(/\b(?:cn|cva|class-variance-authority|design token|theme|variant|--[a-z][\w-]*\s*:|class=['"])/gi)||[]).length;
    if(/\.html?$/i.test(file.path)){landmarks+=(file.content.match(/<(?:main|nav|header|footer|aside|section|article)\b/gi)||[]).length;const lineOf=(index:number)=>file.content.slice(0,index).split(/\r?\n/).length;for(const match of Array.from(file.content.matchAll(/<img\b(?![^>]*\balt\s*=)[^>]*>/gi))){a11y++;add({category:'quality',severity:'high',title:'Static image is missing alternative text',explanation:'The HTML image has no alt attribute for assistive technology.',file_path:file.path,start_line:lineOf(match.index||0),evidence:match[0].slice(0,160),recommendation:'Add meaningful alt text, or alt="" for decorative images.',rule_id:'uiux.html-image-alt',confidence:98});}for(const match of Array.from(file.content.matchAll(/<(?:input|select|textarea)\b(?![^>]*(?:aria-label|aria-labelledby|id)\s*=)[^>]*>/gi))){a11y++;inputs++;add({category:'quality',severity:'medium',title:'Static form control has no detectable label association',explanation:'The HTML control has no id or ARIA accessible-name attribute.',file_path:file.path,start_line:lineOf(match.index||0),evidence:match[0].slice(0,160),recommendation:'Associate a visible label using for/id or add an appropriate accessible name.',rule_id:'uiux.html-form-label',confidence:86});}continue;}
    const source=ts.createSourceFile(file.path,file.content,ts.ScriptTarget.Latest,true,file.path.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.JSX);
    const visit=(node:ts.Node)=>{if(ts.isJsxOpeningElement(node)||ts.isJsxSelfClosingElement(node)){const tag=jsxName(node).toLowerCase(),line=source.getLineAndCharacterOfPosition(node.getStart()).line+1;const text=node.getText(source);if(['main','nav','header','footer','aside','section','article'].includes(tag))landmarks++;if(['input','select','textarea'].includes(tag)){inputs++;if(hasJsxAttribute(node,'aria-label')||hasJsxAttribute(node,'aria-labelledby')||hasJsxAttribute(node,'id'))formLabels++;}
      if(tag==='button'){const hasName=hasJsxAttribute(node,'aria-label')||hasJsxAttribute(node,'title')||(ts.isJsxOpeningElement(node)&&node.parent.children.some(c=>ts.isJsxText(c)&&c.getText().trim().length>0));if(!hasName){iconButtons++;a11y++;add({category:'quality',severity:'medium',title:'Button may lack an accessible name',explanation:'The control has no visible text or detected aria-label/title, so assistive technology may not identify its purpose.',file_path:file.path,start_line:line,evidence:text.slice(0,160),recommendation:'Add concise visible text or an aria-label that describes the action.',rule_id:'uiux.button-name',confidence:82});}}
      if(['input','select','textarea'].includes(tag)&&!hasJsxAttribute(node,'aria-label')&&!hasJsxAttribute(node,'aria-labelledby')&&!hasJsxAttribute(node,'id')){a11y++;add({category:'quality',severity:'medium',title:'Form control has no detectable label association',explanation:'The control lacks id, aria-label, and aria-labelledby attributes.',file_path:file.path,start_line:line,evidence:text.slice(0,160),recommendation:'Associate a visible label using htmlFor/id or provide an appropriate accessible name.',rule_id:'uiux.form-label',confidence:84});}
      if(hasJsxAttribute(node,'autoFocus')){add({category:'quality',severity:'low',title:'Automatic focus may disrupt navigation',explanation:'Automatically moving focus can surprise keyboard and assistive-technology users.',file_path:file.path,start_line:line,evidence:text.slice(0,160),recommendation:'Use autoFocus only when focus movement is essential and predictable.',rule_id:'uiux.autofocus',confidence:72});}}
      ts.forEachChild(node,visit);};visit(source);}
  const uiTests=allTests.filter(f=>/\.[jt]sx$/.test(f.path)).length;const semantic=Math.min(20,landmarks?12+Math.min(8,landmarks):8),accessibility=Math.max(5,25-a11y*4),responsiveScore=responsive>=5?15:responsive>0?10:5,feedbackScore=feedback>=5?15:feedback>0?10:5,consistency=design>=3?15:design>0?11:7,testing=uiTests===0?2:uiTests/uiFiles.length>=.2?10:6;const score=semantic+accessibility+responsiveScore+feedbackScore+consistency+testing;
  if(!responsive)add({category:'quality',severity:'medium',title:'No responsive layout signals detected',explanation:'The UI files contain no detected responsive breakpoint utilities.',file_path:null,start_line:null,evidence:`${uiFiles.length} UI files reviewed`,recommendation:'Define mobile-first layouts and verify behavior at narrow, medium, and wide viewports.',rule_id:'uiux.responsive',confidence:75});if(!feedback)add({category:'quality',severity:'medium',title:'No interaction feedback states detected',explanation:'Loading, error, pending, disabled, toast, or skeleton states were not detected.',file_path:null,start_line:null,evidence:`${uiFiles.length} UI files reviewed`,recommendation:'Represent loading, empty, error, success, and disabled states for important actions.',rule_id:'uiux.feedback',confidence:72});if(!landmarks)add({category:'quality',severity:'medium',title:'No semantic page landmarks detected',explanation:'The analyzed interface does not use main, nav, header, footer, aside, section, or article landmarks.',file_path:null,start_line:null,evidence:`${uiFiles.length} UI files reviewed`,recommendation:'Use semantic landmarks to improve navigation and document structure.',rule_id:'uiux.landmarks',confidence:80});
  const strengths:string[]=[];if(landmarks)strengths.push(`${landmarks} semantic landmark${landmarks===1?'':'s'} detected`);if(responsive>=5)strengths.push('Responsive breakpoint usage is present across the UI');if(feedback>=5)strengths.push('Loading, error, or interaction feedback states are represented');if(design>=3)strengths.push('Reusable styling or variant-system signals were detected');if(uiTests)strengths.push(`${uiTests} UI test file${uiTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(a11y)weaknesses.push(`${a11y} accessibility naming or labeling issue${a11y===1?'':'s'} detected`);if(!responsive)weaknesses.push('No responsive breakpoint signals detected');if(!feedback)weaknesses.push('No loading/error/disabled feedback signals detected');if(!landmarks)weaknesses.push('Semantic page landmarks were not detected');if(!uiTests)weaknesses.push('No UI tests detected');
  const suggestions=Array.from(new Set(findings.filter(f=>f.rule_id.startsWith('uiux.')).map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?68:86,summary:`UI/UX grade: ${frontendGrade(score)} (${score}/100). Reviewed ${uiFiles.length} interface files for semantic structure, accessibility, responsive behavior, interaction feedback, design-system consistency, and UI tests.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{uiFiles:uiFiles.length,semanticLandmarks:landmarks,accessibilityIssues:a11y,responsiveSignals:responsive,feedbackSignals:feedback,designSystemSignals:design,uiTests}};
}

function analyzeAiMl(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):AiMlAssessment{
  const manifests=files.filter(f=>f.path.endsWith('package.json'));let dependencies:Record<string,string>={};for(const file of manifests){try{const value=JSON.parse(file.content);dependencies={...dependencies,...value.dependencies,...value.devDependencies};}catch{/* ignore malformed manifest */}}
  const providerPatterns:Record<string,RegExp>={OpenAI:/\b(openai|@ai-sdk\/openai)\b/i,Anthropic:/\b(@anthropic-ai\/sdk|anthropic|@ai-sdk\/anthropic)\b/i,Google:/\b(@google\/generative-ai|@ai-sdk\/google|gemini)\b/i,Groq:/\b(groq|api\.groq\.com)\b/i,LangChain:/\b(langchain|@langchain\/)\b/i,HuggingFace:/\b(@huggingface\/inference|transformers\.js|sentence-transformers|SentenceTransformer)\b/i,VectorDB:/\b(pinecone|chromadb|weaviate|qdrant|milvus|pgvector)\b/i};
  const dependencyText=Object.keys(dependencies).join(' ')+' '+files.filter(f=>/(^|\/)requirements(?:-[^/]+)?\.txt$/i.test(f.path)).map(f=>f.content).join(' ');const integrationText=dependencyText+' '+files.filter(f=>/\.(ts|tsx|js|jsx|mjs|cjs|py)$/.test(f.path)).map(f=>f.content.slice(0,5000)).join(' ');const providers=Object.entries(providerPatterns).filter(([,pattern])=>pattern.test(integrationText)).map(([name])=>name);
  const aiSignal=/\b(chat\.completions|responses\.create|messages\.create|generateContent|generateText|streamText|embeddings?\.create|vectorStore|similaritySearch|SentenceTransformer|llm\.chat|model\.encode|\.retrieve\s*\(|invoke\s*\(|predict\s*\(|api\.groq\.com)/i;
  const aiFiles=files.filter(f=>/\.(ts|tsx|js|jsx|mjs|cjs|py)$/.test(f.path)&&aiSignal.test(f.content));
  if(!aiFiles.length&&!providers.length)return {applicable:false,score:null,grade:'Not Applicable',confidence:92,summary:'No executable model, embedding, or vector-store integration was detected.',strengths:[],weaknesses:[],suggestions:[],metrics:{aiFiles:0,providers:0,modelCalls:0,validatedOutputs:0,reliabilityControls:0,safetyIssues:0,aiTests:0}};
  let modelCalls=0,validatedOutputs=0,reliabilityControls=0,safetyIssues=0,hardcodedModels=0,promptInterpolation=0;const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('aiml.')).length<24)findings.push(finding(value));};const lineOf=(content:string,index:number)=>content.slice(0,index).split(/\r?\n/).length;
  for(const file of aiFiles){
    const generativePattern=/\b(?:chat\.completions\.create|responses\.create|messages\.create|generateContent|generateText|streamText|llm\.chat|invoke|predict)\s*\(/gi;const generative=Array.from(file.content.matchAll(generativePattern));if(/api\.groq\.com/i.test(file.content))generative.push(...Array.from(file.content.matchAll(/\b(?:client|httpx)\.post\s*\(/gi)));const retrieval=Array.from(file.content.matchAll(/\b(?:embeddings?\.create|similaritySearch|model\.encode|retrieve)\s*\(/gi));const calls=[...generative,...retrieval];modelCalls+=calls.length;
    const validation=/\b(z\.|zod|safeParse|response_format|json_schema|structuredOutput|OutputParser|\.parse\s*\()/i.test(file.content);if(validation)validatedOutputs++;
    const controls=/\b(timeout|AbortController|maxRetries|max_tokens|maxTokens|temperature|rateLimit|retry|backoff)\b/i.test(file.content);if(controls)reliabilityControls++;
    for(const call of generative){const start=call.index||0,near=file.content.slice(Math.max(0,start-500),start+1200);if(!validation){add({category:'quality',severity:'high',title:'Generative model output lacks detected runtime validation',explanation:'Generative output is probabilistic and should not cross application boundaries without validation or a constrained response contract.',file_path:file.path,start_line:lineOf(file.content,start),evidence:call[0],recommendation:'Request structured output and validate it with a strict runtime schema before use.',rule_id:'aiml.output-validation',confidence:84});}if(!controls){add({category:'performance',severity:'medium',title:'No generative-call reliability or cost controls detected',explanation:'The integration lacks detected timeout, retry, token-limit, or rate-limit controls.',file_path:file.path,start_line:lineOf(file.content,start),evidence:call[0],recommendation:'Add request timeouts, bounded retries, token limits, rate limiting, and usage telemetry.',rule_id:'aiml.reliability-controls',confidence:78});}if(/\$\{\s*(?:req|request|body|input|user|query|message)/i.test(near)){promptInterpolation++;safetyIssues++;add({category:'security',severity:'high',title:'Untrusted input is interpolated into a model prompt',explanation:'Direct prompt interpolation increases prompt-injection and instruction-confusion risk.',file_path:file.path,start_line:lineOf(file.content,start),evidence:near.match(/`[^`]*\$\{[^}]+\}[^`]*`/s)?.[0]?.slice(0,180)||call[0],recommendation:'Separate trusted instructions from untrusted content, delimit user data, and constrain allowed model actions.',rule_id:'aiml.prompt-injection',confidence:78});}}
    const model=Array.from(file.content.matchAll(/(?:model\s*:|(?:MODEL|MODEL_NAME)\s*=)\s*['"]([^'"]+)['"]/gi));if(model.length){hardcodedModels+=model.length;add({category:'architecture',severity:'low',title:'Model identifier is hard-coded',explanation:'Hard-coded model selection makes upgrades, fallbacks, and environment-specific configuration harder.',file_path:file.path,start_line:lineOf(file.content,model[0].index||0),evidence:model[0][0],recommendation:'Centralize model selection in validated configuration and record the chosen model per run.',rule_id:'aiml.model-config',confidence:90});}
    if(/console\.(?:log|debug)\s*\([^)]*(?:prompt|messages|response|completion)/i.test(file.content)){safetyIssues++;const match=/console\.(?:log|debug)\s*\([^)]*(?:prompt|messages|response|completion)/i.exec(file.content)!;add({category:'security',severity:'high',title:'Potential model data logged to console',explanation:'Prompts or model responses may contain personal, proprietary, or secret data.',file_path:file.path,start_line:lineOf(file.content,match.index),evidence:match[0].slice(0,160),recommendation:'Log metadata and redacted identifiers instead of raw prompts or responses.',rule_id:'aiml.sensitive-logging',confidence:76});}
  }
  const aiTests=allTests.filter(f=>/\b(ai|llm|model|prompt|embedding|rag|openai|anthropic|gemini)\b/i.test(f.path+' '+f.content.slice(0,1000))).length;const generativeIssues=findings.filter(f=>f.rule_id==='aiml.output-validation').length,reliabilityIssues=findings.filter(f=>f.rule_id==='aiml.reliability-controls').length;const architecture=Math.max(10,20-hardcodedModels*2),prompt=Math.max(8,20-promptInterpolation*5),output=Math.max(6,20-generativeIssues*5),reliability=Math.max(5,15-reliabilityIssues*3),security=Math.max(4,15-safetyIssues*4),testing=aiTests===0?2:aiTests>=2?10:7;const score=architecture+prompt+output+reliability+security+testing;
  const strengths:string[]=[];if(providers.length)strengths.push(`Detected integration with ${providers.join(', ')}`);if(validatedOutputs)strengths.push(`${validatedOutputs} AI module${validatedOutputs===1?' uses':'s use'} structured output validation`);if(reliabilityControls)strengths.push(`${reliabilityControls} AI module${reliabilityControls===1?' includes':'s include'} reliability or cost controls`);if(!safetyIssues)strengths.push('No high-confidence prompt-injection or sensitive-logging issue detected');if(aiTests)strengths.push(`${aiTests} AI-specific test file${aiTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(generativeIssues)weaknesses.push(`${generativeIssues} generative integration${generativeIssues===1?' lacks':'s lack'} detected output validation`);if(reliabilityIssues)weaknesses.push(`${reliabilityIssues} generative integration${reliabilityIssues===1?' lacks':'s lack'} reliability or cost controls`);if(safetyIssues)weaknesses.push(`${safetyIssues} AI safety or privacy issue${safetyIssues===1?'':'s'} detected`);if(hardcodedModels)weaknesses.push(`${hardcodedModels} hard-coded model identifier${hardcodedModels===1?'':'s'} detected`);if(!aiTests)weaknesses.push('No AI-specific tests or evaluation fixtures detected');
  const suggestions=Array.from(new Set(findings.filter(f=>f.rule_id.startsWith('aiml.')).map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?65:84,summary:`AI/ML grade: ${frontendGrade(score)} (${score}/100). Reviewed ${aiFiles.length} integration files and ${modelCalls} model or retrieval calls for architecture, prompts, output contracts, reliability, cost controls, privacy, and testing.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{aiFiles:aiFiles.length,providers:providers.length,modelCalls,validatedOutputs,reliabilityControls,safetyIssues,aiTests}};
}

function analyzeSecurity(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):SecurityAssessment{
  const codeFiles=files.filter(f=>/\.(ts|tsx|js|jsx|mjs|cjs|py)$/.test(f.path));if(!codeFiles.length)return {applicable:false,score:null,grade:'Not Applicable',confidence:95,summary:'No executable JavaScript, TypeScript, or Python source was detected for security review.',strengths:[],weaknesses:[],suggestions:[],metrics:{codeFiles:0,endpointFiles:0,protectedEndpoints:0,criticalIssues:0,highIssues:0,securityTests:0}};
  const endpointFiles=codeFiles.filter(f=>/(^|\/)(api|routes?|controllers?)(\/|$)|(^|\/)route\.[jt]s$/i.test(f.path)||/@(?:app|router)\.(?:get|post|put|patch|delete)\s*\(/.test(f.content));let protectedEndpoints=0;const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('securityreview.')).length<30)findings.push(finding(value));};const lineOf=(content:string,index:number)=>content.slice(0,index).split(/\r?\n/).length;
  for(const file of codeFiles){
    if(endpointFiles.includes(file)){const protectedRoute=/\b(?:authorize|authenticate|getSession|getServerSession|getUser|currentUser|requireUser|verifyToken|jwt\.verify|auth)\s*\(|headers?\.get\s*\(\s*['"]authorization|@clerk\/|next-auth/i.test(file.content);if(protectedRoute)protectedEndpoints++;else add({category:'security',severity:'medium',title:'Endpoint has no detected authentication boundary',explanation:'The route contains no recognizable session, token-verification, or authorization check. Public endpoints should be explicitly documented and rate-limited.',file_path:file.path,start_line:1,evidence:`Endpoint file: ${file.path}`,recommendation:'Require authentication and resource-level authorization, or explicitly mark the route public and enforce abuse controls.',rule_id:'securityreview.endpoint-auth',confidence:68});}
    const secret=/\b(?:api[_-]?key|secret|token|password|private[_-]?key)\s*[:=]\s*['"](?!test|example|placeholder|changeme)([A-Za-z0-9_\-\/+=]{16,})['"]/ig;for(const match of Array.from(file.content.matchAll(secret))){add({category:'security',severity:'critical',title:'Potential hard-coded credential',explanation:'A credential-like value appears directly in source code.',file_path:file.path,start_line:lineOf(file.content,match.index||0),evidence:match[0].replace(match[1],'[REDACTED]'),recommendation:'Revoke the exposed credential, move it to a secret store, and scan repository history.',rule_id:'securityreview.hardcoded-secret',confidence:82});}
    const execution=/\b(?:eval|Function)\s*\(|\b(?:exec|execSync|spawn|spawnSync)\s*\(\s*`[^`]*\$\{/g;for(const match of Array.from(file.content.matchAll(execution))){const nearby=file.content.slice(Math.max(0,(match.index||0)-500),(match.index||0)+300),guarded=/ALLOW|fullmatch|\.match\s*\(|__builtins__\s*['"]?\s*:\s*\{\}/i.test(nearby);add({category:'security',severity:guarded?'medium':'critical',title:guarded?'Guarded dynamic evaluation remains a sensitive boundary':'Dynamic code or command execution',explanation:guarded?'The eval call appears constrained by an allow-list and empty built-ins, reducing exploitability, but parser edge cases make dynamic evaluation a security-sensitive design.':'Dynamic execution can become code or command injection when any interpolated value is attacker-controlled.',file_path:file.path,start_line:lineOf(file.content,match.index||0),evidence:match[0].slice(0,180),recommendation:guarded?'Replace eval with a small arithmetic parser to remove the dynamic-execution boundary entirely.':'Remove dynamic evaluation; invoke allow-listed commands with argument arrays and strict validation.',rule_id:'securityreview.dynamic-execution',confidence:guarded?82:88});}
    const cors=/['"]Access-Control-Allow-Origin['"]\s*:\s*['"]\*['"]|origin\s*:\s*['"]\*['"]/i.exec(file.content);if(cors)add({category:'security',severity:'high',title:'Wildcard CORS policy detected',explanation:'Allowing every origin can expose browser-accessible data or actions to untrusted sites.',file_path:file.path,start_line:lineOf(file.content,cors.index),evidence:cors[0],recommendation:'Allow-list trusted origins and review whether credentials or sensitive responses are exposed.',rule_id:'securityreview.cors-wildcard',confidence:88});
    const weakHash=/createHash\s*\(\s*['"](?:md5|sha1)['"]\s*\)/i.exec(file.content);if(weakHash)add({category:'security',severity:'high',title:'Weak cryptographic hash detected',explanation:'MD5 and SHA-1 are unsuitable for security-sensitive integrity or credential storage.',file_path:file.path,start_line:lineOf(file.content,weakHash.index),evidence:weakHash[0],recommendation:'Use a modern construction appropriate to the purpose, such as SHA-256 for integrity or Argon2/scrypt for passwords.',rule_id:'securityreview.weak-hash',confidence:96});
    const random=/Math\.random\s*\(\s*\)/g;for(const match of Array.from(file.content.matchAll(random))){const nearby=file.content.slice(Math.max(0,(match.index||0)-100),(match.index||0)+150);if(/token|secret|password|otp|nonce|session|id/i.test(nearby))add({category:'security',severity:'high',title:'Non-cryptographic randomness used for a security-like value',explanation:'Math.random is predictable and must not generate tokens, OTPs, nonces, or session identifiers.',file_path:file.path,start_line:lineOf(file.content,match.index||0),evidence:nearby.replace(/\s+/g,' ').slice(0,180),recommendation:'Use crypto.randomUUID or cryptographically secure random bytes.',rule_id:'securityreview.insecure-random',confidence:84});}
    const ssrf=/fetch\s*\(\s*(?:`[^`]*\$\{\s*(?:url|uri|host|input|query|body)|(?:url|uri|input|query|body)\b)/i.exec(file.content);if(ssrf)add({category:'security',severity:'high',title:'Potential server-side request forgery boundary',explanation:'A network destination appears to be derived from input without a detected destination allow-list.',file_path:file.path,start_line:lineOf(file.content,ssrf.index),evidence:ssrf[0].slice(0,180),recommendation:'Parse destinations, enforce HTTPS and an explicit host allow-list, and block private/link-local address ranges.',rule_id:'securityreview.ssrf',confidence:70});
  }
  const securityTests=allTests.filter(f=>/\b(security|auth|authorization|permission|injection|xss|csrf|cors|secret)\b/i.test(f.path+' '+f.content.slice(0,1500))).length;const relevant=findings.filter(f=>f.category==='security');const critical=relevant.filter(f=>f.severity==='critical').length,high=relevant.filter(f=>f.severity==='high').length,medium=relevant.filter(f=>f.severity==='medium').length;
  const secureCoding=Math.max(5,25-critical*8-high*4-medium*2),authentication=endpointFiles.length?Math.max(5,20-Math.max(0,endpointFiles.length-protectedEndpoints)*3):16,secrets=Math.max(4,15-relevant.filter(f=>/secret|credential|logging/i.test(f.rule_id+' '+f.title)).length*5),injection=Math.max(5,20-relevant.filter(f=>/injection|sql|ssrf|dynamic|dangerous-html|prompt/i.test(f.rule_id)).length*4),configuration=Math.max(4,10-relevant.filter(f=>/cors|env|config|hash|random/i.test(f.rule_id+' '+f.title)).length*2),testing=securityTests===0?2:securityTests>=2?10:7;const score=secureCoding+authentication+secrets+injection+configuration+testing;
  const strengths:string[]=[];if(protectedEndpoints)strengths.push(`${protectedEndpoints} endpoint file${protectedEndpoints===1?' includes':'s include'} an authentication signal`);if(!critical)strengths.push('No critical high-confidence security issue detected');if(!relevant.some(f=>/secret|credential/i.test(f.rule_id+' '+f.title)))strengths.push('No hard-coded credential pattern detected');if(!relevant.some(f=>/sql|dynamic-execution|ssrf/i.test(f.rule_id)))strengths.push('No high-confidence command, SQL, or SSRF injection pattern detected');if(securityTests)strengths.push(`${securityTests} security-focused test file${securityTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(critical)weaknesses.push(`${critical} critical security finding${critical===1?'':'s'}`);if(high)weaknesses.push(`${high} high-severity security finding${high===1?'':'s'}`);if(endpointFiles.length>protectedEndpoints)weaknesses.push(`${endpointFiles.length-protectedEndpoints} endpoint file${endpointFiles.length-protectedEndpoints===1?' has':'s have'} no detected authentication boundary`);if(!securityTests)weaknesses.push('No security-focused tests detected');
  const suggestions=Array.from(new Set(relevant.map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?65:85,summary:`Security grade: ${frontendGrade(score)} (${score}/100). Reviewed ${codeFiles.length} source files and ${endpointFiles.length} endpoint files for authentication, secrets, injection, unsafe execution, cryptography, configuration, privacy, and security tests.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{codeFiles:codeFiles.length,endpointFiles:endpointFiles.length,protectedEndpoints,criticalIssues:critical,highIssues:high,securityTests}};
}

function analyzeProduct(files:SourceFile[],allTests:SourceFile[],findings:FindingInput[],truncated:boolean):ProductAssessment{
  const code=files.filter(f=>/\.(ts|tsx|js|jsx|mjs|cjs|py)$/.test(f.path));const appFiles=code.filter(f=>/(^|\/)(app|pages|routes?|api|backend|static|screens?|views?|commands?|cli)(\/|$)/i.test(f.path));const manifests=files.filter(f=>f.path.endsWith('package.json'));let packageData:Record<string,unknown>={};for(const file of manifests){try{packageData={...packageData,...JSON.parse(file.content)};}catch{/* ignore malformed manifest */}}
  const isLibrary=Boolean(packageData.main||packageData.exports)&&!appFiles.length;const applicable=appFiles.length>0||(!isLibrary&&code.length>1);if(!applicable)return {applicable:false,score:null,grade:'Not Applicable',confidence:88,summary:isLibrary?'A reusable library was detected without an application surface, so no product-delivery grade was assigned.':'No application or product surface was detected.',strengths:[],weaknesses:[],suggestions:[],metrics:{applicationFiles:0,documentedCapabilities:0,feedbackStates:0,operabilitySignals:0,deliverySignals:0,productTests:0}};
  const readme=files.find(f=>f.path.toLowerCase()==='readme.md');const readmeText=readme?.content||'';const documentedCapabilities=['install','usage','feature','configuration','environment','deploy','test'].filter(term=>new RegExp(`\\b${term}`, 'i').test(readmeText)).length;const combined=appFiles.map(f=>f.content).join('\n');const feedbackStates=(combined.match(/\b(?:loading|pending|skeleton|spinner|empty state|no results|error|retry|toast|success|disabled)\b/gi)||[]).length;const operabilitySignals=(combined.match(/\b(?:health|metrics|telemetry|logger|logging|sentry|opentelemetry|trace|audit)\b/gi)||[]).length;const feedbackLoops=(combined.match(/\b(?:analytics|posthog|segment|feedback|survey|track\s*\(|capture\s*\()\b/gi)||[]).length;const deliveryFiles=files.filter(f=>/(^|\/)(Dockerfile|docker-compose[^/]*|vercel\.json|fly\.toml|render\.yaml|Procfile|\.github\/workflows\/[^/]+|railway\.json)$/i.test(f.path));const deliverySignals=deliveryFiles.length;const productTests=allTests.filter(f=>/(e2e|integration|playwright|cypress|user|flow|journey)/i.test(f.path+' '+f.content.slice(0,1200))).length;const todos=appFiles.reduce((n,f)=>n+(f.content.match(/\b(?:TODO|FIXME|HACK)\b/g)||[]).length,0);const errorBoundary=appFiles.some(f=>/ErrorBoundary|error\.tsx|componentDidCatch/i.test(f.path+' '+f.content));
  const add=(value:FindingInput)=>{if(findings.filter(f=>f.rule_id.startsWith('product.')).length<20)findings.push(finding(value));};
  if(documentedCapabilities<3)add({category:'documentation',severity:'medium',title:'Product setup and usage are under-documented',explanation:'The README does not clearly cover enough of installation, usage, features, configuration, environment, deployment, and testing.',file_path:readme?.path||null,start_line:readme?1:null,evidence:`${documentedCapabilities}/7 product documentation signals detected`,recommendation:'Document the value proposition, primary workflows, setup, configuration, testing, and deployment.',rule_id:'product.documentation',confidence:82});
  if(!feedbackStates)add({category:'quality',severity:'high',title:'No user-facing feedback states detected',explanation:'The application surface has no detected loading, empty, error, retry, success, or disabled-state language.',file_path:null,start_line:null,evidence:`${appFiles.length} application files reviewed`,recommendation:'Design explicit loading, empty, success, error, retry, and disabled states for critical workflows.',rule_id:'product.feedback-states',confidence:76});
  if(!errorBoundary&&appFiles.some(f=>/\.[jt]sx$/.test(f.path)))add({category:'quality',severity:'medium',title:'No UI error boundary detected',explanation:'Unexpected rendering failures may replace the interface without a controlled recovery path.',file_path:null,start_line:null,evidence:'No ErrorBoundary, componentDidCatch, or error.tsx signal detected',recommendation:'Add route-level or feature-level error boundaries with recovery actions and diagnostic reporting.',rule_id:'product.error-boundary',confidence:76});
  if(!operabilitySignals)add({category:'architecture',severity:'medium',title:'No operational visibility signals detected',explanation:'Health checks, structured logging, metrics, tracing, or error monitoring were not detected.',file_path:null,start_line:null,evidence:`${appFiles.length} application files reviewed`,recommendation:'Add structured logs, health checks, error monitoring, and metrics for critical workflows.',rule_id:'product.operability',confidence:72});
  if(!deliverySignals)add({category:'documentation',severity:'medium',title:'No automated delivery configuration detected',explanation:'No deployment manifest, container definition, or CI workflow was found in the analyzed snapshot.',file_path:null,start_line:null,evidence:'0 delivery configuration files detected',recommendation:'Add reproducible build/deployment configuration and a CI validation workflow.',rule_id:'product.delivery',confidence:82});
  if(!feedbackLoops)add({category:'quality',severity:'low',title:'No product feedback or analytics loop detected',explanation:'No event analytics, product feedback, or user-research capture signal was found.',file_path:null,start_line:null,evidence:'0 feedback-loop signals detected',recommendation:'Define a privacy-conscious measurement plan for activation, completion, failure, and retention.',rule_id:'product.feedback-loop',confidence:65});
  if(todos>10)add({category:'implementation',severity:'medium',title:'High concentration of unfinished-work markers',explanation:'Numerous TODO/FIXME/HACK markers can indicate incomplete product flows or accumulated delivery debt.',file_path:null,start_line:null,evidence:`${todos} unfinished-work markers`,recommendation:'Triage markers into tracked work, resolve critical-path items, and remove stale comments.',rule_id:'product.todo-density',confidence:78});
  const value=Math.min(20,8+documentedCapabilities*2),completeness=Math.max(8,20-Math.min(8,todos)),experience=feedbackStates?Math.min(20,12+Math.min(8,feedbackStates)):6,operability=Math.min(15,operabilitySignals?10+Math.min(5,operabilitySignals):5),delivery=Math.min(15,deliverySignals?11+Math.min(4,deliverySignals):6),validation=productTests?Math.min(10,6+productTests*2):feedbackLoops?5:2;const score=value+completeness+experience+operability+delivery+validation;
  const strengths:string[]=[];if(documentedCapabilities>=5)strengths.push('README covers major product setup and usage concerns');if(feedbackStates)strengths.push(`${feedbackStates} user-feedback state signal${feedbackStates===1?'':'s'} detected`);if(operabilitySignals)strengths.push('Operational health, logging, metrics, or monitoring signals are present');if(deliverySignals)strengths.push(`${deliverySignals} automated delivery configuration${deliverySignals===1?'':'s'} detected`);if(productTests)strengths.push(`${productTests} product-flow or integration test${productTests===1?'':'s'} detected`);
  const weaknesses:string[]=[];if(documentedCapabilities<3)weaknesses.push('Product setup, workflows, and operations are under-documented');if(!feedbackStates)weaknesses.push('Critical user feedback states were not detected');if(!operabilitySignals)weaknesses.push('No operational visibility signals detected');if(!deliverySignals)weaknesses.push('No reproducible delivery configuration detected');if(!productTests)weaknesses.push('No product-flow or integration tests detected');
  const suggestions=Array.from(new Set(findings.filter(f=>f.rule_id.startsWith('product.')).map(f=>f.recommendation).filter((v):v is string=>Boolean(v)))).slice(0,4);
  return {applicable:true,score,grade:frontendGrade(score),confidence:truncated?62:82,summary:`Product grade: ${frontendGrade(score)} (${score}/100). Reviewed ${appFiles.length} application files for value clarity, workflow completeness, user feedback, operability, delivery readiness, measurement, and product-level tests.`,strengths:strengths.slice(0,4),weaknesses:weaknesses.slice(0,4),suggestions,metrics:{applicationFiles:appFiles.length,documentedCapabilities,feedbackStates,operabilitySignals,deliverySignals,productTests}};
}
export function analyzeSnapshot(snapshot:RepositorySnapshot){
  const findings:FindingInput[]=[];const code=snapshot.files.filter(f=>/\.[cm]?[jt]sx?$/.test(f.path));const executable=snapshot.files.filter(f=>/\.(?:[cm]?[jt]sx?|py)$/.test(f.path));const tests=executable.filter(f=>/(^|\/)(__tests__|test|tests)(\/|$)|\.(test|spec)\.[jt]sx?$|test_[^/]+\.py$|_test\.py$/.test(f.path));
  const configs=new Set(snapshot.files.map(f=>f.path.toLowerCase())); const totalLines=executable.reduce((n,f)=>n+f.lines,0);let functionCount=0,typedAny=0,unsafeHtml=0,consoleCount=0,largeFunctions=0;
  for(const file of code){
    const kind=/tsx$/.test(file.path)?ts.ScriptKind.TSX:/jsx$/.test(file.path)?ts.ScriptKind.JSX:ts.ScriptKind.TS;const source=ts.createSourceFile(file.path,file.content,ts.ScriptTarget.Latest,true,kind);
    const visit=(node:ts.Node)=>{if(ts.isFunctionDeclaration(node)||ts.isFunctionExpression(node)||ts.isArrowFunction(node)||ts.isMethodDeclaration(node)){functionCount++;const start=source.getLineAndCharacterOfPosition(node.getStart()).line+1,end=source.getLineAndCharacterOfPosition(node.getEnd()).line+1;if(end-start+1>80){largeFunctions++;findings.push(finding({category:'quality',severity:'medium',title:'Large function',explanation:`Function spans ${end-start+1} lines, increasing review and testing cost.`,file_path:file.path,start_line:start,evidence:source.text.slice(node.getStart(),node.getStart()+100).replace(/\s+/g,' '),recommendation:'Split the function into focused units with explicit responsibilities.',rule_id:'quality.large-function',confidence:95}));}}
      if(node.kind===ts.SyntaxKind.AnyKeyword)typedAny++;
      if((ts.isPropertyAccessExpression(node)&&node.name.text==='dangerouslySetInnerHTML')||(ts.isJsxAttribute(node)&&node.name.getText(source)==='dangerouslySetInnerHTML')){unsafeHtml++;const line=source.getLineAndCharacterOfPosition(node.getStart()).line+1;findings.push(finding({category:'security',severity:'high',title:'Unsafe HTML rendering surface',explanation:'dangerouslySetInnerHTML can introduce cross-site scripting when content is not rigorously sanitized.',file_path:file.path,start_line:line,evidence:node.getText(source).slice(0,160),recommendation:'Avoid raw HTML or sanitize it with a proven allow-list sanitizer.',rule_id:'security.dangerous-html',confidence:90}));}
      if(ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)&&node.expression.expression.getText(source)==='console'){consoleCount++;}
      ts.forEachChild(node,visit);};visit(source);
    if(file.lines>400)findings.push(finding({category:'architecture',severity:'medium',title:'Oversized source module',explanation:`This module contains ${file.lines} lines and likely combines multiple responsibilities.`,file_path:file.path,start_line:1,evidence:`${file.lines} lines`,recommendation:'Extract cohesive modules and keep public boundaries small.',rule_id:'architecture.large-module',confidence:90}));
  }
  if(tests.length===0)findings.push(finding({category:'testing',severity:'high',title:'No JavaScript/TypeScript tests detected',explanation:'No conventional test files were found among the analyzed source files.',file_path:null,start_line:null,evidence:`0 test files across ${code.length} source files`,recommendation:'Add unit tests for domain logic and integration tests for critical workflows.',rule_id:'testing.no-tests',confidence:95}));
  const ratio=code.length?tests.length/code.length:0;if(tests.length>0&&ratio<0.1)findings.push(finding({category:'testing',severity:'medium',title:'Low test-file ratio',explanation:'The repository has relatively few test files compared with implementation files.',file_path:null,start_line:null,evidence:`${tests.length} test files / ${code.length} code files`,recommendation:'Prioritize tests around critical and failure-prone modules.',rule_id:'testing.low-ratio',confidence:80}));
  if(typedAny>10)findings.push(finding({category:'quality',severity:'medium',title:'Frequent explicit any usage',explanation:'Frequent any annotations weaken TypeScript guarantees.',file_path:null,start_line:null,evidence:`${typedAny} any keywords`,recommendation:'Replace any with domain types, unknown, or validated generics.',rule_id:'quality.explicit-any',confidence:85}));
  if(!Array.from(configs).some(p=>p.includes('github/workflows/')))findings.push(finding({category:'testing',severity:'low',title:'No GitHub Actions workflow detected',explanation:'Automated validation was not found in the repository tree.',file_path:null,start_line:null,evidence:'No .github/workflows files analyzed',recommendation:'Run lint, type checks, and tests in CI for every change.',rule_id:'testing.no-ci',confidence:75}));
  if(!configs.has('readme.md'))findings.push(finding({category:'documentation',severity:'medium',title:'README missing',explanation:'No root README.md was detected.',file_path:null,start_line:null,evidence:'README.md absent',recommendation:'Document purpose, setup, configuration, testing, and deployment.',rule_id:'docs.no-readme',confidence:95}));
  if(consoleCount>20)findings.push(finding({category:'quality',severity:'low',title:'Heavy console usage',explanation:'Numerous console calls can make production observability inconsistent.',file_path:null,start_line:null,evidence:`${consoleCount} console calls`,recommendation:'Use a structured logger with environment-aware levels.',rule_id:'quality.console',confidence:80}));
  const frontend=analyzeFrontend(snapshot.files,tests,findings,snapshot.truncated);
  const backend=analyzeBackend(snapshot.files,tests,findings,snapshot.truncated);
  const uiUx=analyzeUiUx(snapshot.files,tests,findings,snapshot.truncated);
  const aiMl=analyzeAiMl(snapshot.files,tests,findings,snapshot.truncated);
  const security=analyzeSecurity(snapshot.files,tests,findings,snapshot.truncated);
  const product=analyzeProduct(snapshot.files,tests,findings,snapshot.truncated);
  const penalties={implementation:0,architecture:0,quality:0,testing:0,security:0,performance:0,documentation:0};const cost={info:0,low:1,medium:3,high:6,critical:10};for(const f of findings)penalties[f.category]+=cost[f.severity];
  const hasTs=code.some(f=>/\.tsx?$/.test(f.path));const readme=snapshot.files.find(f=>f.path.toLowerCase()==='readme.md');
  const definitions:Array<[CategoryScore['category'],number,string]>=[['implementation',20,`${code.length} code files and ${functionCount} functions analyzed`],['architecture',15,`${snapshot.treeCount} repository files mapped`],['quality',15,hasTs?'TypeScript is present':'JavaScript codebase'],['testing',15,`${tests.length} test files detected`],['security',10,`${unsafeHtml} unsafe HTML surfaces detected`],['performance',10,'Static efficiency signals evaluated'],['documentation',15,readme?`README contains ${readme.lines} lines`:'Root README not found']];
  const scores=definitions.map(([category,max_score,rationale])=>{const noExecutable=executable.length===0;const score=noExecutable?(category==='documentation'&&readme?Math.min(5,max_score):0):Math.max(Math.round(max_score*.35),max_score-penalties[category]);return {category,max_score,score,confidence:snapshot.truncated?70:90,rationale:noExecutable?(category==='documentation'&&readme?'Documentation-only repository: limited README credit; no executable project was available.':'Not scorable because no executable source files were detected.'):rationale};});
  return {findings,scores,frontend,backend,uiUx,aiMl,security,product,metrics:{codeFiles:executable.length,testFiles:tests.length,totalLines,functionCount,typedAny,consoleCount,largeFunctions},languages:Array.from(new Set(executable.map(f=>f.language.split(' ')[0])))};
}
