import { z } from 'zod';
import type { AnalysisFinding, CategoryScore, Evaluation, EvaluationAgent, ManualAiReview } from '../types/database';

const evidenceRefs=z.array(z.string().uuid()).max(12);
export const manualAiResponseSchema=z.object({
  schema_version:z.literal('1.0'),evaluation_id:z.string().uuid(),commit_sha:z.string().regex(/^[a-f0-9]{40}$/i),model_label:z.string().min(1).max(100),review_summary:z.string().min(20).max(4000),confidence:z.number().int().min(0).max(100),
  architecture_observations:z.array(z.object({title:z.string().min(3).max(200),explanation:z.string().min(10).max(2000),impact:z.enum(['low','medium','high']),evidence_refs:evidenceRefs,confidence:z.number().int().min(0).max(100)})).max(12),
  prioritized_risks:z.array(z.object({title:z.string().min(3).max(200),severity:z.enum(['low','medium','high','critical']),explanation:z.string().min(10).max(2000),evidence_refs:evidenceRefs,mitigation:z.string().min(10).max(2000)})).max(12),
  recommendations:z.array(z.object({title:z.string().min(3).max(200),priority:z.union([z.literal(1),z.literal(2),z.literal(3)]),rationale:z.string().min(10).max(2000),evidence_refs:evidenceRefs,implementation_steps:z.array(z.string().min(3).max(500)).min(1).max(8)})).max(12),
  rubric_advice:z.array(z.object({category:z.enum(['implementation','architecture','quality','testing','security','performance','documentation']),suggested_delta:z.number().int().min(-3).max(3),rationale:z.string().min(10).max(1000),evidence_refs:evidenceRefs})).max(7),
}).strict();

const responseShape={schema_version:'1.0',evaluation_id:'UUID copied exactly from request',commit_sha:'40-character SHA copied exactly from request',model_label:'ChatGPT model name shown in the UI',review_summary:'20-4000 character evidence-grounded synthesis',confidence:'integer 0-100',architecture_observations:[{title:'string',explanation:'string',impact:'low | medium | high',evidence_refs:['finding UUIDs from evidence_catalog'],confidence:'integer 0-100'}],prioritized_risks:[{title:'string',severity:'low | medium | high | critical',explanation:'string',evidence_refs:['finding UUIDs'],mitigation:'string'}],recommendations:[{title:'string',priority:'1 | 2 | 3',rationale:'string',evidence_refs:['finding UUIDs'],implementation_steps:['specific step']}],rubric_advice:[{category:'implementation | architecture | quality | testing | security | performance | documentation',suggested_delta:'integer -3 through 3; advisory only',rationale:'string',evidence_refs:['finding UUIDs']}]};

export function createManualAiRequest(evaluation:Evaluation,agents:EvaluationAgent[],scores:CategoryScore[],findings:AnalysisFinding[]){
  return {schema_version:'1.0',task:'Produce an evidence-grounded architectural and engineering review. When instructor_assignment exists, evaluate its free-form brief and resolve needs_ai checks using only supplied evidence. Return JSON only. Do not use markdown fences. Do not invent files, behavior, or evidence IDs. Empty arrays are valid when evidence is insufficient. Rubric advice is advisory and cannot change deterministic scores automatically.',evaluation:{id:evaluation.id,repository:evaluation.repo_name||evaluation.repo_url,commit_sha:evaluation.repo_stats.commit_sha,summary:evaluation.summary,deterministic_score:evaluation.final_score,confidence:evaluation.confidence_level,repository_metrics:evaluation.repo_stats},instructor_assignment:evaluation.assignment_spec?{spec:evaluation.assignment_spec,deterministic_results:evaluation.assignment_results}:null,category_scores:scores,specialist_reviews:agents.map(a=>({specialist:a.agent_name,score:a.score,summary:a.findings,strengths:a.strengths,weaknesses:a.weaknesses,suggestions:a.suggestions})),evidence_catalog:findings.slice(0,80).map(f=>({id:f.id,category:f.category,severity:f.severity,title:f.title,explanation:f.explanation,file_path:f.file_path,start_line:f.start_line,evidence:f.evidence,recommendation:f.recommendation,confidence:f.confidence})),required_response_schema:responseShape};
}

export function validateManualAiResponse(input:unknown,evaluation:Evaluation,findings:AnalysisFinding[]):ManualAiReview{
  const value=manualAiResponseSchema.parse(input);if(value.evaluation_id!==evaluation.id)throw new Error('Response evaluation_id does not match this evaluation.');if(value.commit_sha!==evaluation.repo_stats.commit_sha)throw new Error('Response commit_sha does not match the analyzed commit.');const known=new Set(findings.map(f=>f.id));const refs=[...value.architecture_observations,...value.prioritized_risks,...value.recommendations,...value.rubric_advice].flatMap(item=>item.evidence_refs);const unknown=refs.filter(id=>!known.has(id));if(unknown.length)throw new Error(`Unknown evidence reference: ${unknown[0]}`);return value;
}
